/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'ProcessWebhook': EventHandler<{ webhookId: string; projectId: string; method: string; headers: Record<string, string | Array<string>>; body: unknown; receivedAt: string }, never>
    'CaptureWebhook': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { webhookId: string; status: string }>, { topic: 'webhook-captured'; data: { webhookId: string; projectId: string; method: string; headers: Record<string, string | Array<string>>; body: unknown; receivedAt: string } }>
    'ProcessGreeting': EventHandler<{ timestamp: string; appName: string; greetingPrefix: string; requestId: string }, never>
    'HelloAPI': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { message: string; status: string; appName: string }>, { topic: 'process-greeting'; data: { timestamp: string; appName: string; greetingPrefix: string; requestId: string } }>
  }
    
}