/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'ProcessGreeting': EventHandler<{ timestamp: string; appName: string; greetingPrefix: string; requestId: string }, never>
    'HelloAPI': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { message: string; status: string; appName: string }>, { topic: 'process-greeting'; data: { timestamp: string; appName: string; greetingPrefix: string; requestId: string } }>
    'ReplayWebhook': ApiRouteHandler<{ targetUrl: string }, ApiResponse<200, { webhookId: string; status: string }> | ApiResponse<404, { error: string }>, { topic: 'webhook-forward'; data: never }>
    'ForwardWebhook': EventHandler<{ webhookId: string; targetUrl: string; headers: Record<string, string | Array<string>>; body: unknown }, never>
    'ProcessWebhook': EventHandler<{ webhookId: string; projectId: string; method: string; headers: Record<string, string | Array<string>>; body: unknown; receivedAt: string }, never>
    'GetWebhook': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { id: string; projectId: string; method: string; headers: Record<string, string | Array<string>>; body: unknown; receivedAt: string; status: 'received' | 'forwarded' | 'failed'; forwardedAt?: string; targetUrl?: string; errorMessage?: string }> | ApiResponse<404, { error: string }>, never>
    'CaptureWebhook': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { webhookId: string; status: string }>, { topic: 'webhook-captured'; data: never }>
    'ListWebhooks': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { webhooks: Array<{ id: string; projectId: string; method: string; headers: Record<string, string | Array<string>>; body: unknown; receivedAt: string; status: 'received' | 'forwarded' | 'failed'; forwardedAt?: string; targetUrl?: string; errorMessage?: string }>; total: number; limit: number; offset: number }>, never>
  }
    
}